apiVersion: v2
name: apitable
description: A Helm chart for installing APITable and all of these dependencies
type: application
version: 0.1.0
dependencies:
- name: redis
  version: "~17.8.3"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
- name: rabbitmq
  version: "~11.10.3"
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.enabled
- name: minio
  version: "~12.1.10"
  repository: "https://charts.bitnami.com/bitnami"
  condition: minio.enabled
- name: mysql
  version: "~9.6.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enabled