{{- if .Values.database.PGZalando.enabled }}
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: {{ include "directus.fullname" . }}

spec:
  teamId: {{ .Values.database.PGZalando.teamId }}
  postgresql:
    version: "15"
  numberOfInstances: 1
  volume:
    size: {{ .Values.database.storageSize }}
  users:
    {{ .Values.database.user }}: []
  databases:
    {{ .Values.database.database }}: {{ .Values.database.user }}
{{- end }}
