apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "apitable.fullname" . }}-upstreams"
  labels:
    {{- include "apitable.labels" . | nindent 4 }}
data:
  ups-backend-server.conf: |
    upstream backend  {
      server {{ include "apitable.fullname" . }}-backend-server:{{ .Values.backendServer.service.port }};
    }
  ups-imageproxy.conf: |
    upstream imageproxy{
      server {{ include "apitable.fullname" . }}-image-proxy:{{ .Values.imageProxy.service.port }};
    }
  ups-minio.conf: |
    upstream minio {
      server {{ .Release.Name }}-minio:9000;
    }
  ups-room.conf: |
    upstream room  {
      server {{ include "apitable.fullname" . }}-room-server:{{ .Values.roomServer.service.ports.http }};
    }
    upstream socket  {
      hash $remote_addr consistent;
      server {{ include "apitable.fullname" . }}-room-server:{{ .Values.roomServer.service.ports.socketUrl }};
    }
    upstream socketRoom  {
      hash $remote_addr consistent;
      server {{ include "apitable.fullname" . }}-room-server:{{ .Values.roomServer.service.ports.socketRoom }};
    }
  ups-web-server.conf: |
    upstream web-server {
      server {{ include "apitable.fullname" . }}-web-server:{{ .Values.webServer.service.port }};
    }

