apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "apitable.fullname" . }}-pre-init-db"
  labels:
    {{- include "apitable.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apitable.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apitable.serviceAccountName" . }}
      securityContext:
        {{- .Values.initDB.podSecurityContext | default .Values.podSecurityContext | toYaml | nindent 8 }}
      containers:
      - name: pre-init-db
        image: "{{ .Values.initDB.image.repository }}:{{ .Values.initDB.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.initDB.image.pullPolicy }}        
        securityContext:
          {{- .Values.initDB.securityContext | default .Values.securityContext | toYaml | nindent 10 }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: MYSQL_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: MYSQL_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: MYSQL_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: MYSQL_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: MYSQL_PASSWORD
        - name: DATABASE_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: "{{ include "apitable.fullname" . }}-envs"
              key: DATABASE_TABLE_PREFIX
        - name: ACTION
          value: "releaseLocks"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}