apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "apitable.fullname" . }}-envs"
  labels:
    {{- include "apitable.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  AWS_ACCESS_SECRET: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  MAIL_PASSWORD: {{ "" | b64enc | quote }}